name: Yakindu SCT C++11 Timer Service.
on: [push]

jobs:
   CPP-Check:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: sudo apt update -y
         - name: Install needed components
           run: sudo apt install -y libgtest-dev qt5-qmake qt5-default cppcheck
         - name: Install Google Test
           run: sudo bin/install-gtest.sh
         - name: Build
           run: bin/build-examples.sh
